version: "3.4"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - softrobot_volume:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  softrobot_access:
    build:
      context: .
    image: softrobot_access
    container_name: softrobot_access
    environment:
      - jwtPrivateKey=jwtPrivateKey
      - noreplyEmailAdd=noreply@qenvi.com
      - emailPass=noQEN-2022!!
      - mongoDbAddress=mongodb
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=&&Cant#getit9*-#
      # - MONGODB_ADD=127.0.0.1
      # - DB_NAME=softrobot
    ports:
      - "${PORT}:5000"
    links:
      - mongodb

volumes:
  softrobot_volume:

    
