version: "3.4"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=&SQenvi5*-
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    command: mongod

  softrobot_access:
    build:
      context: .
    image: softrobot_access
    container_name: softrobot_access
    environment:
      - JWT_PRIVATE_KEY=jwtPrivateKey
      - NOREPLY_EMAIL_ADDR=noreply@qenvi.com
      - EMAIL_PASS=noQEN-2022!!
      - MONGODB_ADDR=mongodb
      - USERNAME_CONNEXION_DB=root
      - PASS_CONNEXION_DB=&SQenvi5*-
    ports:
      - "${PORT}:5000"
    links:
      - mongodb

volumes:
  db:
